title: AmexPL. Asociación Mexicana del Perro Lobo
logo: /assets/img/logo.png
description: Sitio oficial de la Asociación Mexicana del Perro Lobo.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
